[build]
  command = "chmod +x build.sh && go run main.go"
  functions = "functions"
  publish = "./"

[build.environment]
  GO_IMPORT_PATH = "github.com/Lann892/website-back-go"
  GO111MODULE = "on"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/gateway/:splat"
  status = 200